Ocelot-Social-Community/Ocelot-Social

webapp/assets/_new/styles/tokens.scss
webapp/components/ImageUploader/ImageUploader.vue
webapp/locales/de.json
webapp/locales/en.json
webapp/locales/es.json
webapp/locales/fr.json
webapp/locales/it.json
webapp/locales/nl.json
webapp/locales/pl.json
webapp/locales/pt.json
webapp/locales/ru.json

to show the supported image formats in the ImageUploader of the editor 
- fixes #1949

feat: 🍰 Show Supported Image Formats Implemented

---

webapp/components/LoginForm/LoginForm.spec.js
webapp/components/LoginForm/LoginForm.vue

The pull request modifies the password input field to include an Icon that reveals or hides the password and simultaneously updates the Icon to reflect the state of password field. 
- fixes #2434

[Feature] Show/Hide Password Icon - Issue # 2434

---

webapp/components/LoginForm/LoginForm.vue
webapp/locales/de.json
webapp/locales/en.json
webapp/store/auth.js

Checks if a cookie with the JWT exists after login. If not, an error message is toasted, saying that no cookie could be set.
- fixes #4080

Throw Error When No Cookie Can Be Set

---

webapp/constants/metadata.js
webapp/nuxt.config.js
webapp/plugins/apollo-config.js
webapp/store/auth.js

The name of the cookie used to store the JWT is now configured in the `webapp/constants/metadata.js`
- fixes #4090

Name of Cookie Is Set in metadata.js

---

webapp/package.json
webapp/yarn.lock

This reverts commit a72e3e3747b37f66b4a6033ee719e324e5dea278.
- None

Revert "Bump tiptap-extensions from 1.28.8 to 1.34.0 in /webapp"

---

backend/src/middleware/slugify/uniqueSlug.js
backend/src/middleware/slugify/uniqueSlug.spec.js

This PR is a replacement for PR #3676. The previous PR was from the old HC repository and has issues with the merge. The setting for the slug package has been set to properly resolve the umlauts to their proper two letter encoding. 
- fixes #3504

[WIP] fix: 🍰 Issue #3504 umlaut encoding #3676

---

backend/src/config/index.js
backend/src/db/clean.js
backend/src/middleware/email/emailMiddleware.js
backend/src/middleware/sentryMiddleware.js
backend/src/schema/resolvers/images/images.js
webapp/Dockerfile.maintenance
webapp/config/index.js
webapp/nuxt.config.js

Refactor the config handling for front- and backend. 
- fixes #4131

Refactor config

---

webapp/components/PostTeaser/PostTeaser.vue

Removes the categories from the post teaser as we decided not to use them for now anymore.
- fixes #4156

refactor: Remove Catgeories From Post Teaser

---

backend/src/jwt/encode.js

The server keeps the JWT for 2 years instead of 1 day.
- fixes #4258

fix: JWT Expires In  2 Years

---

backend/src/schema/resolvers/users/location.spec.js
webapp/components/Editor/Editor.spec.js
webapp/components/Editor/Editor.vue

- Changed suggestion list filtering to search for prefix instead of substring
- Sorted results by length so stricter matches show up on top
- Added spacebar selection functionality for mentions
- Fixes #2635 
- None

fix: 🍰 Suggestion List Filter

---

webapp/components/LoginForm/LoginForm.vue
webapp/components/Registration/RegistrationSlideCreate.vue
webapp/components/ShowPassword/ShowPassword.spec.js
webapp/components/ShowPassword/ShowPassword.vue

Pull request pulls out logic for the ShowPassword into a component for use in various password fields. 
#4312

feat: 🍰 Show Password Component 

---

webapp/components/Editor/MenuBarButton.vue

Fix menu legend menu bar button without click event.
We have overseen a console warning in the browser and also by running the webapp tests:
- fixes #3673

fix: 🍰 Fix Menu Legend Menu Bar Button Without Click Event

---

backend/src/config/links.js
webapp/components/PageFooter/PageFooter.spec.js
webapp/components/PageFooter/PageFooter.vue
webapp/constants/links.js
webapp/locales/de.json
webapp/locales/en.json
webapp/locales/html/de/code-of-conduct.html
webapp/locales/html/de/data-privacy.html
webapp/locales/html/de/faq.html
webapp/locales/html/de/imprint.html
webapp/locales/html/de/index.js
webapp/locales/html/de/organization.html
webapp/locales/html/de/support.html
webapp/locales/html/de/terms-and-conditions.html
webapp/locales/html/en/code-of-conduct.html
webapp/locales/html/en/data-privacy.html
webapp/locales/html/en/faq.html
webapp/locales/html/en/imprint.html
webapp/locales/html/en/index.js
webapp/locales/html/en/organization.html
webapp/locales/html/en/support.html
webapp/locales/html/en/terms-and-conditions.html
webapp/middleware/authenticated.js
webapp/nuxt.config.js
webapp/pages/organization.spec.js
webapp/pages/organization.vue
webapp/pages/support.spec.js
webapp/pages/support.vue

Landing Page etc.
- fixes #4549

🍰 feat: Landing Page etc.

---

webapp/components/Embed/EmbedComponent.vue

Fix embed iframe width and height CSS.
- fixes #4881

fix: 🍰 Fix Embed iframe Width And Height CSS

---

webapp/components/Editor/nodes/Hashtag.js
webapp/components/Editor/plugins/eventHandler.js

we use the oembed library, in the provider.json ... you can see what is used. 
I cannot say at this point whether this is current. 
As far as d.tube is concerned, nothing has changed. 
but in the url you can copy from the browser is a /#!/ 
this causes the problem. 
the only solution i found now is to remove this. 
but i don't think this is a good solution. it should happen in the provider.json ... but there we have some problem in the code ... 
the hashtag function is not the problem
- fixes #4896 
note: 
if a link from facebook shows the message 'please log in', then the user from whom this source comes has set it that way.

fix: 🍰 Replace Hashtag In d.tube Url

---

.github/workflows/publish.yml
backend/src/config/index.js
backend/src/db/clean.js
backend/src/db/seed.js

Automatic deployment to `stage.ocelot.social` on push to (merge into) `master` branch.
See:
- https://docs.digitalocean.com/products/kubernetes/how-to/deploy-using-github-actions/
- https://docs.digitalocean.com/tutorials/build-and-deploy-your-first-image-to-your-first-cluster/
- especially:
- see example https://github.com/do-community/example-doctl-action
- see example https://github.com/do-community/example-doctl-action/blob/main/.github/workflows/workflow.yaml
- fixes #5065
- follow up #5093
Commands for `branded`:
```bash
kubectl -n default set image deployment/ocelot-webapp container-ocelot-webapp=ocelotsocialnetwork/webapp-branded:latest
kubectl -n default set image deployment/ocelot-backend container-ocelot-backend=ocelotsocialnetwork/backend-branded:latest
kubectl -n default set …
```

chore: 🍰 Automatic Deployment To `stage.ocelot.social` On Push To `master` Branch

---

backend/src/middleware/permissionsMiddleware.js
backend/src/middleware/permissionsMiddleware.spec.js
backend/src/schema/resolvers/comments.spec.js
backend/src/schema/resolvers/donations.spec.js
backend/src/schema/resolvers/emails.spec.js
backend/src/schema/resolvers/follow.spec.js
backend/src/schema/resolvers/moderation.spec.js
backend/src/schema/resolvers/notifications.spec.js
backend/src/schema/resolvers/posts.spec.js
backend/src/schema/resolvers/registration.spec.js
backend/src/schema/resolvers/reports.spec.js
backend/src/schema/resolvers/rewards.spec.js
backend/src/schema/resolvers/shout.spec.js
backend/src/schema/resolvers/socialMedia.spec.js
backend/src/schema/resolvers/user_management.spec.js
backend/src/schema/resolvers/users.spec.js
backend/src/schema/resolvers/users/mutedUsers.spec.js
webapp/components/ContributionForm/ContributionForm.spec.js
webapp/components/DeleteData/DeleteData.spec.js
webapp/components/Modal/DisableModal.spec.js
webapp/components/ReleaseModal/ReleaseModal.spec.js

- Fixes https://github.com/Ocelot-Social-Community/Ocelot-Social/issues/5203

feat: 🍰 Change Error Message With `Authorised` To `Authorized` All Over The Place To Have American English

---

webapp/components/FilterMenu/CategoriesMenu.vue
webapp/layouts/default.vue
webapp/locales/de.json
webapp/locales/en.json

If categories are active, a menu point "Topics" appears to the left of the search field. Clicking on the menu, it opens a dropdown, where active topics can be selected

feat: Topics Menu

---

backend/src/db/seed.js
backend/src/schema/resolvers/groups.js
backend/src/schema/resolvers/groups.spec.js

Hidden groups content shall not be visible or listed for none or pending members in backend.
- fixes #5059

 feat: 🍰 Hidden Groups Shall Not Be Visible For None Or Pending Members In Backend

---

backend/package.json
backend/yarn.lock
package.json
yarn.lock

Upgrade neode from v^0.4.7 to v^0.4.8 in backend and main folder.
So that we don't have a unnecessary difference between the branches `master` and `5059-epic-groups`.
- fixes #5333

chore: 🍰 Update Neode From v^0.4.7 To v^0.4.8 In Backend

---

webapp/components/Group/GroupForm.vue

when update edit a group, disable submit button if data are not according to schema
- fixes #5472

refactor: 🍰 Disable Submit Button On group Update Changed Error

---

webapp/components/PageFooter/PageFooter.vue
webapp/constants/headerMenu.js
webapp/layouts/default.vue

fist step,  if mobile,  footer menu to heder menu
- fixes #4732

feat: 🍰 Mobile Footer Menu To Header Menu

---

webapp/components/_new/generic/BaseCard/BaseCard.vue

**Earlier Long words were not wrapped in GroupProfile and UserProfile.**
**Now the Long words are wrapped in GroupProfile and UserProfile.**
- fixes   https://github.com/Ocelot-Social-Community/Ocelot-Social/issues/5427

fix: [WIP] 🍰 Long Words Are Being Wrapped Now

---

backend/src/middleware/permissionsMiddleware.js
backend/src/schema/resolvers/postsInGroups.spec.js

Ensure that no posts in groups can be commented by users that are not member of the group.
- relates #5462

feat: Restrict Comments on Posts in Groups

---

webapp/components/CategoriesSelect/CategoriesSelect.vue
webapp/components/FilterMenu/CategoriesFilter.vue
webapp/mixins/sortCategoriesMixin.js
webapp/pages/group/_id/_slug.vue
webapp/pages/post/_id/_slug/index.vue

feat(webapp): 🍰 Sort Categories By Name

---

backend/src/middleware/login/loginMiddleware.js
backend/src/schema/resolvers/emails.js
backend/src/schema/resolvers/emails.spec.js
backend/src/schema/resolvers/helpers/existingEmailAddress.js
backend/src/schema/resolvers/registration.js
backend/src/schema/resolvers/registration.spec.js

Do not throw errors when emails exists on registration or add email address.
- fixes #5878

fix(backend): do not expose registered emails on registration

---

webapp/locales/de.json
webapp/locales/en.json
webapp/pages/map.vue

refactor(webapp): set legend to map

---

webapp/components/AvatarMenu/AvatarMenu.vue
webapp/components/HeaderMenu/HeaderMenu.vue
webapp/pages/index.vue

the first 50px are excluded from the scrolling hide mechanism.
this should solve the turning off of the navbar in case of a bounce effect when scrolling back slightly.   
- fixes #5953

fix(webapp): navbar disappears when scrolling to top

---

.github/workflows/publish.yml
.github/workflows/test.yml

There are lots of deprecated warnings that we should update our actions to run in node 16
```
Node.js 12 actions are deprecated.
Please update the following actions to use Node.js 16:
* actions/checkout@v2, 
* actions/upload-artifact@v2.
For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```
- None

chore(other): update github actions for node 16

---

webapp/pages/map.vue

As user when I search an address in the Mapbox a blue marker appears but the blue marker is also used by groups.
After discussion with @Tirokk we agreed to remove additional markers.
- fixes #5980

fix(webapp): remove additional markers from map

---

backend/src/schema/resolvers/groups.js

The cypher query for groups is order to oldest first, expected would be to be newest first
- fixes #6066

feat(webapp): change order of groups to new first

---

webapp/components/PostTeaser/PostTeaser.vue

Fixes the position of the post ribbons. Now they are positioned as a content-divider between the user-info and the post image.
- fixes #3157

fix(webapp): fix ribbons position 

---

backend/src/middleware/notifications/notificationsMiddleware.js
backend/src/middleware/notifications/notificationsMiddleware.spec.js
backend/src/schema/resolvers/notifications.js
backend/src/schema/resolvers/notifications.spec.js
backend/src/schema/types/enum/ReasonNotification.gql
backend/src/schema/types/type/NOTIFIED.gql
webapp/components/Notification/Notification.vue
webapp/components/NotificationsTable/NotificationsTable.vue
webapp/graphql/User.js
webapp/locales/de.json
webapp/locales/en.json
webapp/pages/group/_id/_slug.vue

feat(backend): notifications for groups

---

webapp/components/Group/GroupForm.vue
webapp/components/Select/ActionRadiusSelect.spec.js
webapp/components/Select/ActionRadiusSelect.vue

refactor(webapp): make action radius select in group form a reusable component

---

deployment/README.deployment.md

Add description for script usage in deployment readme.
- fixes #6328

docs(other): add description for script usage in deployment readme

---

deployment/scripts/cluster.reseed.sh
deployment/src/kubernetes/README.md

reference to dist folder when its called build
- None

fix(other): typescript fix regarding dist/build folder 2

---

backend/src/db/seed.js
backend/src/middleware/notifications/notificationsMiddleware.js
backend/src/middleware/validation/validationMiddleware.js
backend/src/models/Post.js
backend/src/schema/resolvers/moderation.js
backend/src/schema/resolvers/notifications.js
backend/src/schema/resolvers/reports.js
backend/src/schema/resolvers/searches.js

* sets the property `postType` to `Article` as default
* seeds one active event
* seeds one passed event
* seeds one event started but not ended
- None

feat(backend): seed events

---

.github/workflows/test-e2e.yml

At the moment each e2e test job runs about 17 - 30 min.
Main reason is building the SUT docker images (about 15 min) in each e2e test job.
Now one preparation job builds images once. The e2e test jobs run 15 min less now.
This way the used runners will be freed much earlier for other workflow jobs.

refactor(other): use cached docker images in github e2e flow to decrease run time of e2e test job runs

---

backend/src/graphql/messages.ts
backend/src/schema/types/type/Message.gql
webapp/graphql/Messages.js

chat messages - order by `indexId` instead of `createdAt`
- None

refactor(backend): chat messages - order by indexId instead of createdAt

---

backend/src/schema/types/type/Room.gql

profile query fix to return the correct user avatar not the first found
Before:
After:
- None

fix(backend): profile query fix

---

.github/workflows/test-e2e.yml

With the CI caching mechanism  jobs can no longer be restarted  since the deletion of the ci-cache fails (cleanup job).

fix(other): set workflow not to fail while deleting cache

---

backend/src/graphql/messages.ts
backend/src/graphql/rooms.ts
webapp/graphql/Messages.js
webapp/graphql/Rooms.js

aligned backend and frontend queries, show last message and unread count in room list
- None

feat(webapp): show last message and unread count in room list

---

webapp/components/Chat/Chat.vue
webapp/layouts/default.vue
webapp/pages/chat.vue
webapp/pages/profile/_id/_slug.vue

On open chat room page close or on change profile and click chat change small chat.
- fixes #6589
- fixes #6551

feat(webapp): on open chat room page close or on change profile and click chat change small chat

---

webapp/components/Chat/Chat.vue
webapp/graphql/Messages.js

fix lastMessage to contain proper values
- None

fix(webapp): fix lastMessage to contain proper values

---

webapp/locales/de.json
webapp/locales/en.json

Change general search hint.
- relates #6610

feat(webapp): change general search hint

---

webapp/components/generic/SelectUserSearch/SelectUserSearch.vue

In the search user component used in Group Admin and chat create new room searches after 4 characters.
This sets it to 3 characters
- fixes #6635

fix(webapp): start search of user after three characters (chat new room, add group member)

---

webapp/components/Chat/Chat.vue

- Set style of chat component to 'scoped'
Fix wrong font in whole network comming from chat component.
- fixes #6669

fix(webapp): fix wrong font in whole network comming from chat component

---

webapp/pages/map.vue

This PR modifies the base link for a group in maps from "group" to "groups".
- fixes #6687

fix(webapp): fix the group link in the map

---

webapp/components/DonationInfo/DonationInfo.spec.js
webapp/components/Group/GroupMember.spec.js
webapp/components/LoginForm/LoginForm.spec.js
webapp/components/PostTeaser/PostTeaser.spec.js
webapp/pages/index.spec.js
webapp/pages/login.spec.js
webapp/pages/logout.spec.js
webapp/pages/map.spec.js
webapp/pages/password-reset.spec.js
webapp/pages/post/edit/_id.spec.js
webapp/pages/registration.spec.js
webapp/pages/terms-and-conditions-confirm.spec.js

In the webapp Jest v29.5 is used.
Several method from our unit tests are deprecated in this Jest versin
Replace deprecatedmethods with current equivalent
- blocked-by #6809

refactor(webapp): replace deprecated jest methods in webapp unit tests

---

README.md
deployment/scripts/cluster.install.sh
deployment/src/kubernetes/DigitalOcean.md
deployment/src/kubernetes/README.md

Fix and refine docs and add kubernetes cluster installation script.
- fixes #6795

fix(other): fix and refine docs and add kubernetes cluster installation script

---

backend/jest.config.js
backend/src/schema/resolvers/notifications.spec.ts

Exclude all the files from the `src/db` folder from coverage. Remove `Promise.all` from notifications spec.
- None

feat(backend): coverage backend to 90%

---

backend/src/constants/groups.ts
backend/src/schema/resolvers/groups.spec.ts
webapp/constants/groups.js

Change group 'DESCRIPTION_WITHOUT_HTML_LENGTH_MIN = 3', was '50'.
- relates #6923

feat(other): change group description length min

---

webapp/constants/links.js

Fix footer links.
- fixes #6865

fix(webapp): fix footer links

---

.github/workflows/test-backend.yml
.github/workflows/test-e2e.yml
.github/workflows/test-webapp.yml
backend/src/schema/resolvers/posts.spec.ts
backend/src/schema/resolvers/users/location.spec.ts
frontend/.github/workflows/frontend.deploy.docs.yml

Due to Github Runners migration from docker compose v1 to v2 this summer (see [here](https://github.com/actions/runner-images/issues/9864#issuecomment-2114371013)) all our Dependabot bump PRs failed. (e.g. [the cheerio update](https://github.com/Ocelot-Social-Community/Ocelot-Social/actions/runs/10327804316/job/28593638175) in backend).
This PR migrates all our workflow files to using compose v1.

refactor(workflow): replace docker-compose by docker compose in workflow files

---

.github/workflows/publish.yml

Using the latest commit hash did not work.
- None

fix(workflow): reset pkgdeps/git-tag-action to v3.0.0 in publish.yml

---

backend/src/schema/resolvers/users/location.spec.ts

A longer known recurring issue:
```
FAIL src/schema/resolvers/users/location.spec.ts
● userMiddleware › UpdateUser › creates a Location node with localized city/state/country names
expect(received).toEqual(expected) // deep equality
- Expected  - 2
+ Received  + 2
@@ -1,11 +1,11 @@
Array [
Object {
"city": Object {
"id": StringContaining "place",
-       "lat": 48.87682,
-       "lng": 9.634519,
+       "lat": 48.874393,
+       "lng": 9.634301,
"name": "Welzheim",
"nameDE": "Welzheim",
"nameEN": "Welzheim",
"nameES": "Welzheim",
"nameFR": "Welzheim",
219 |           }
220 |         }),
> 221 |       ).toEqual(newlyCreatedNodesWithLocales)
|         ^
222 |     })
223 |   })
224 | })
at src/schema/resolvers/users/location.spec.ts:221:9
at fulfilled …
```

fix(backend): fix geodata in mapbox-related resolver test

---

backend/README.md
webapp/README.md

Currently we have the Node version 2[0.12.1](url) set (see [.nvmrc](https://github.com/Ocelot-Social-Community/Ocelot-Social/blob/master/.nvmrc)).
This pull request updates that information in the readme files.

refactor(other): change set node version in readme files

---

.github/dependabot.yml

In the dependabot configuration the grouping of all Vue related packages does not work for the update process.
- relates #7951

refactor(webapp): degroup vue packages in dependabot

---

.github/dependabot.yml

In the dependabot configuration the grouping of all SASS related packages does not work for the update process.
- relates #7958

refactor(webapp): degroup sass packages in dependabot

---

.github/workflows/publish.yml

remove the requirement for non-existent job in publish workflow.
Motivation: The workflow fails on master still, since it has no run-condition
See https://github.com/Ocelot-Social-Community/Ocelot-Social/actions/runs/13617378876
- None

fix(workflow): remove the requirement for non-existent job in publish workflow

---

package.json
scripts/release.sh

release script also update helmchart versions
To have congruence a release also updates the helmchart version. This utilizes sed to replace the coresponding string. The `sed` command is not present on windows and could prevent a windows user to use the release functionality out of the box.
The release functionality is also externalized into its own script `scripts/release.sh`.
- None

feat(other): release script also update helmchart versions

---

backend/src/graphql/posts.ts
backend/src/middleware/permissionsMiddleware.ts
backend/src/middleware/slugifyMiddleware.spec.ts
backend/src/schema/resolvers/comments.ts
backend/src/schema/resolvers/observePosts.spec.ts
backend/src/schema/resolvers/posts.spec.ts
backend/src/schema/resolvers/posts.ts
backend/src/schema/resolvers/postsInGroups.spec.ts
backend/src/schema/types/type/Post.gql
webapp/graphql/Fragments.js
webapp/graphql/PostMutations.js

We want to have the possibility to observe posts:
* a newly created post is always observed by the author
* the first comment to a post makes the commenting user observing the post
* provides the `toggleObservePost` mutation to switch observation on and off
* unit tests that show the correct behavior, e.g. commenting a post that I do not observe for  a second time, does not alter the state of observation
* adds `observedByMe` property to the Post type
* provides a blueprint for the mutation in the webapp
- relates #8280

feat(backend): observe posts

---

backend/src/middleware/permissionsMiddleware.ts
backend/src/models/User.ts
backend/src/schema/resolvers/users.spec.ts
backend/src/schema/resolvers/users.ts
backend/src/schema/types/enum/OnlineStatus.gql
backend/src/schema/types/type/User.gql
webapp/graphql/updateOnlineStatus.js
webapp/nuxt.config.js
webapp/plugins/onlineStatus.js

Regularly update online status of user.
This saves a timestamp on the user as `lastActiveAt` and a status `lastOnlineStatus` which can either be `online` or àway`.
The combination of the `lastActiveAt` timestamp and the `lastOnlineStatus` allows to determine if the user is reachable via notification or an email is the way to go.
In the screenshot you can see a call as `away` when the tab is switched and a call as `online` when the tab is activated again. The next entry is the regular ping every 30 seconds.
The `lastActiveAt` timestamp is set whenever the token of the user is seen querying the backend. A mechanic, which was already in place.
The Database looks like this:
- contributes to https://github.com/Ocelot-Social-Community/Ocelot-Social/issues/8290

feat(webapp): track online status

---

webapp/locales/de.json

Refine group muting locales.
Some locales are to long to fit nicely into the button.
- None

fix(webapp): refine group muting locales

---

backend/src/middleware/notifications/notificationsMiddleware.posts-in-groups.spec.ts
backend/src/middleware/notifications/notificationsMiddleware.spec.ts
backend/src/middleware/notifications/notificationsMiddleware.ts

BLOCKED works in both directions. Meaning a blocked user does not receive notifications from me.
MUTED only works in one direction. Meaning a muted user may receive notifications from me.
- relates #8388

feat(backend): do not notify blocked or muted users

---

README.md
docker-compose.yml

When you follow the documentation, your `docker compose up` will fail because a `.env` file is referenced that doesn't exist yet. The documentation mentions a `.env.template` file, so I guess that one was deleted but the documentation not updated.

fix(docu): remove required but missing `frontend/.env`

---

webapp/layouts/blank.vue

the basic layout "blank" contained a hardcoded style attribute with a padding, which was a way too big for mobile.
This PR fixes the issue.
- None

fix(webapp): fixed padding for mobile in basic layout

---

backend/src/config/index.ts
backend/src/emails/sendEmail.ts
webapp/config/index.js
webapp/plugins/i18n.js

default language configurable.
This also Applies to the backend for the emails.
This also fixes browser detection.
Configure docker
```
service:
webapp:
environment:
- LANGUAGE_DEFAULT=de
- LANGUAGE_FALLBACK=de
backend:
environment:
- LANGUAGE_DEFAULT=de
```
`LANGUAGE_DEFAULT=de` in the webapp is very hard to test since it requires the browser not to send any valid language
`LANGUAGE_FALLBACK=de` - go to http://localhost:3000/registration?method=invite-code&inviteCode=ABCDEF and set to `ES` -> see German  default text
With `LANGUAGE_FALLBACK=en` or nothing configures (as it is the default):
For the backend `LANGUAGE_DEFAULT=de` register with `locale=fr` selected in the frontend and you should receive a German mail. When repeating the step with `locale=en` set in the frontend you should …

feat(webapp): default language configurable

---

backend/package.json
backend/src/graphql/resolvers/images/images.spec.ts
backend/src/graphql/resolvers/images/images.ts
backend/yarn.lock

I think we can merge this already. The S3 client dependency is outdated
and since the code is behind a feature flag it doesn't get executed. Why
not merge it then?

build(backend): upgrade outdated S3 client

---

webapp/pages/post/_id/_slug/index.vue

fix broken observe on post
Due to missing tests & problematic refactoring, posts could no longer be observed and the new observe state beeing indicated without reloading the page.
This reverts parts of https://github.com/Ocelot-Social-Community/Ocelot-Social/pull/8598 to fix the problem
- relates https://github.com/Ocelot-Social-Community/Ocelot-Social/pull/8598

fix(webapp): fix broken observe on post

---

backend/src/plugins/apolloLogger.spec.ts
backend/src/plugins/apolloLogger.ts

This is the log of login:
```
2025-07-01 11:16:45.083 DEBUG   /src/plugins/apolloLogger.ts:22 mainLogger      Apollo Request 5ee29e84 "mutation ($email: String!, $password: String!) {\n  login(email: $email, password: $password)\n}\n" {"email":"admin@example.org","password":"***"}
2025-07-01 11:16:45.201 DEBUG   /src/plugins/apolloLogger.ts:41 mainLogger      Apollo Response 5ee29e84 {"login":"token"}
```
see unit test
- None

fix(backend): mask jwt token in log

---

backend/.env.template
docker-compose.override.yml
docker-compose.yml

Except if you enable it with:
```
DEBUG=neo4j-graphql-js
```
.. in your `backend/.env`

refactor(backend): silence neo4j-graphql-js
