- .travis.yml
- backend/Dockerfile
- deployment/helm/human-connection/templates/deployments/deployment-backend.yaml
- deployment/helm/human-connection/values.yaml
- deployment/human-connection/deployment-backend.yaml
- deployment/human-connection/deployment-neo4j.yaml
- deployment/human-connection/deployment-web.yaml
- deployment/human-connection/maintenance/README.md
- deployment/human-connection/maintenance/deployment-maintenance.yaml
- deployment/human-connection/templates/configmap.template.yaml
- deployment/legacy-migration/README.md
- deployment/legacy-migration/maintenance-worker.yaml
- deployment/legacy-migration/maintenance-worker/Dockerfile
- deployment/minikube/README.md
- deployment/volumes/README.md
- deployment/volumes/neo4j-offline-backup/README.md
- deployment/volumes/neo4j-online-backup/README.md
- deployment/volumes/velero/README.md
- docker-compose.build-and-test.yml
- docker-compose.maintenance.yml
- docker-compose.override.yml
- docker-compose.yml
- scripts/docker_push.sh
- webapp/Dockerfile
- webapp/Dockerfile.maintenance
Setting up the Travis builds …
- fixes #3921
> chore:  🍰 Set Up Travis Builds

- neo4j/Dockerfile
Switch Neo4j To Community Edition.
- fixes #3935
> chore: 🍰 Switch Neo4j To Community Edition

- backend/README.md
Adding a information for the node version in use by us and how to switch between different node versions locally.
> feat: Node Version Recommendation In backend/README.md

- webapp/components/SocialMedia/SocialMedia.spec.js
- webapp/components/SocialMedia/SocialMedia.vue
- webapp/pages/profile/_id/_slug.vue
> feat: 🔥 Displaying Social Media Favicons On Profile Page

- webapp/store/auth.test.js
The cookie test must be mocked to get the test running again
> Mock Cookie In Auth.test.js

- webapp/middleware/authenticated.js
- webapp/pages/logout.vue
- on logout force to go to login page
- start with register page
- fixes #4089
> start_on_register

- docker-compose.override.yml
- docker-compose.yml
If code was changed by the developer in backend and webapp live reload was not executed.
*This maybe just a quick fix.*
- None
> chore: 🍰 Quick Fix Of Live Reload By Nuxt For Docker-Compose

- backend/src/schema/resolvers/inviteCodes.spec.js
Due to missing automated tests, we merged a small bug into master. Here is the fix.
> bug: hotfix for invite codes

- backend/package.json
- backend/src/middleware/index.js
- backend/src/middleware/languages/languages.js
- backend/src/middleware/languages/languages.spec.js
- backend/src/schema/resolvers/posts.spec.js
- backend/src/schema/types/type/Post.gql
- backend/yarn.lock
- webapp/components/ContributionForm/ContributionForm.spec.js
- webapp/components/ContributionForm/ContributionForm.vue
- webapp/graphql/PostMutations.js
Using detect language package (https://www.npmjs.com/package/languagedetect) to detect the language of a post automatically.
- fixes #4147
> feat: Auto Detect Language Of Posts

- backend/src/schema/resolvers/statistics.spec.js
Adding a reset of the db before all tests should avoid the random fail of the test.
- fixes #4178
> bug: DB Reset At Start Of Statistics Test In Backend

- webapp/config/index.js
- webapp/nuxt.config.js
- make cookie time configurable (default: 2 years)
- make cookie https setting configurable (default true in production)
- ensure cookie is set to `path: /` to fix redirect problem
- fixes https://github.com/Ocelot-Social-Community/Ocelot-Social/issues/4182
> Fix cookie

- webapp/components/FilterMenu/FilterMenu.vue
Disable all filters we do not want to use by now.
- fixes #4155
> refactor: Disbale Emoji, Language And Catgeory Filter

- backend/src/db/factories.js
- backend/src/models/Image.js
- backend/src/schema/resolvers/images.js
- backend/src/schema/resolvers/images/images.js
- backend/src/schema/types/type/Image.gql
- webapp/components/ContributionForm/ContributionForm.spec.js
- webapp/components/ContributionForm/ContributionForm.vue
- webapp/components/ImageUploader/ImageUploader.spec.js
- webapp/components/ImageUploader/ImageUploader.vue
- webapp/graphql/Fragments.js
- webapp/locales/de.json
- webapp/locales/en.json
- webapp/pages/post/_id/_slug/index.vue
Cropping of jpgs is optional. No more clicks needed to upload an image. Formats that cannot be cropped so far, have no option to be cropped.
- fixes #1934
> feat: Image Cropping Is Optional

- .github/workflows/publish.yml
> - add latest tag for neo4j

- webapp/components/features/FollowList/FollowList.vue
removed focus on input field of follow lists to avoid scrolling
> fix: Scrolling On Profile Page

- webapp/assets/_new/styles/tokens.scss
- webapp/components/Editor/ContentViewer.story.js
- webapp/components/Editor/Editor.vue
- yarn.lock
Adaption of PR #3493 .
- fixes #3492
- close #3493
> fix: 🐛 Adapted Editor List Styles

- .github/workflows/publish.yml
- backend/Dockerfile
- neo4j/Dockerfile
- webapp/Dockerfile
This PR corrects the version style used in releasing & tagging to follow [SemVer 2.0](https://semver.org/spec/v2.0.0.html)
- None
> Correct version style

- backend/src/middleware/email/templateBuilder.js
- backend/src/middleware/email/templates/emailVerification.html
- backend/src/middleware/email/templates/resetPassword.html
- backend/src/middleware/email/templates/wrongAccount.html
- Refactor e-mail templates to look at least nice regarding to the logo.
- Fix an issue with the `wrongAccountTemplate` were the organisation etc. was not placed in the template.
- fixes #4349
> refactor: 🍰 Refactor E-Mail Templates

- .github/workflows/test.yml
- backend/package.json
- docker-compose.test.yml
- webapp/package.json
> frontend + backend coverage tests

- .github/ISSUE_TEMPLATE/question.md
- CONTRIBUTING.md
- README.md
Correct discord links and divers.
- fixes #4459
> docs: 🍰 Correct Discord Links And Divers

- CONTRIBUTING.md
Correct ‚Contribution.md'.
- fixes #4465
> docs: 🍰 Correct 'Contribution.md'

- backend/src/config/index.js
> fixed wrong env variable

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/devops_ticket.md
- .github/ISSUE_TEMPLATE/epic.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/ISSUE_TEMPLATE/refactor_tickets.md
- Introduces EPIC as issue type
- Simplifies all other Issue types
> New Issue type EPIC

- README.md
> Spelling Change

- webapp/components/LoginForm/LoginForm.vue
- webapp/components/Registration/RegistrationSlider.vue
- webapp/pages/registration.spec.js
Centered the Login-form and created a separate class for registration-slider
- #4481
> Centered the login-form

- README.md
Change in main README.md the db commands for docker.
- None
> docs: 🍰 Change README.md DB Commands For Docker

- README.md
- Adds test technologies.
- Adds introduction video link.
- None
> docs: 🍰 Refine Main README.md With Test Tech Stack And Video Link

- webapp/components/Editor/MenuLegend.vue
Change Tip Tap editor legend hover for open the menu to a click.
- fixes #4691
> fix: 🍰 Change Tip Tap Editor Legend  Hover To Click

- backend/src/db/factories.js
- backend/src/db/seed.js
- webapp/components/CommentList/CommentList.story.js
- webapp/components/_new/generic/TabNavigation/TabNavigator.story.js
- webapp/storybook/helpers.js
Replace deleted faker package – change to import again.
Followup of #4973 .
- fixes #4962
> bug: 🍰 Replace Deleted Faker Package – Change To Import Again

- backend/src/schema/resolvers/users/location.spec.js
Fix location backend test.
- fixes #5033
> Fix location backend test

- DOCKER_MORE_CLOSELY.md
- SUMMARY.md
- backend/Dockerfile
- webapp/Dockerfile
Fix `ocelotsocialnetwork/webapp:latest` and `ocelotsocialnetwork/backend:latest` running locally and on start in cluster.
- fixes #5066
> chore: 🍰 Fix `ocelotsocialnetwork/webapp:latest` And `ocelotsocialnetwork/backend:latest` On Start In Cluster

- DOCKER_MORE_CLOSELY.md
- neo4j/README.md
Neo4j add docu for important commands to `neo4j/README.md`.
- fixes #5087
> docs: 🍰 Add Neo4j Docu For Important Commands

- webapp/components/PageFooter/PageFooter.vue
change link to version-link on github
- fixes #5089
> change footer version-link

- .github/workflows/publish.yml
Betters automatic deployment to `stage.ocelot.social` on push to `master` Branch.
- relates #5093
!!! This don't fixes the issue perfectly !!!
see isssue #5093
> chore: 🍰 Betters Automatic Deployment To `stage.ocelot.social` On Push To `master` Branch

- backend/.env.template
- backend/src/config/index.js
- backend/src/schema/resolvers/posts.js
- webapp/.env.template
- webapp/components/ContributionForm/ContributionForm.spec.js
- webapp/components/ContributionForm/ContributionForm.vue
- webapp/components/PostTeaser/PostTeaser.spec.js
- webapp/components/PostTeaser/PostTeaser.vue
- webapp/components/_new/features/SearchResults/SearchResults.spec.js
- webapp/config/index.js
- webapp/graphql/Fragments.js
- webapp/pages/post/_id.spec.js
- webapp/pages/post/_id/_slug/index.spec.js
- webapp/pages/post/_id/_slug/index.vue
- webapp/pages/post/create.spec.js
- webapp/pages/post/edit/_id.spec.js
- webapp/pages/registration.spec.js
Include the old category mechanism, if the option `ACTIVE_CATEGORIES` is true.
- None
> feat: Make Categories Optional

- backend/src/schema/resolvers/users.spec.js
- backend/src/schema/types/enum/UserRole.gql
- backend/src/schema/types/type/User.gql
- webapp/graphql/admin/Roles.js
Rename `UserGroup` to `UserRole`.
- fixes #5142
> refactor: 🍰 Rename `UserGroup` To `UserRole`

- backend/src/db/graphql/comments.js
- backend/src/db/graphql/posts.js
- backend/src/db/graphql/userManagement.js
- backend/src/db/seed.js
- backend/src/schema/resolvers/user_management.spec.js
Add groups to seeding.
- fixes #5183
> chore: 🍰 Add Groups To Seeding

- backend/package.json
In backend tests add informations for memory usage and open handles / unsolved promises.
- fixes #5181
See https://stackoverflow.com/questions/62885390/my-jests-tests-are-leaking-memory-how-can-i-fix-this
> chore: 🍰 Add `--logHeapUsage` To Jest Test Call

- .github/PULL_REQUEST_TEMPLATE.md
- Fixes https://github.com/Ocelot-Social-Community/Ocelot-Social/issues/5207
> chore: 🍰 Fix typo in PULL_REQUEST_TEMPLATE.md file

- webapp/pages/password-reset/change-password.spec.js
Fix test description from `enter-nonce.vue` to `change-password`.
- fixes #5216
> fix: 🍰 Fix Test Description From `enter-nonce.vue` To `change-password`

- backend/src/middleware/permissionsMiddleware.js
- backend/src/schema/resolvers/users.js
- backend/src/schema/resolvers/users.spec.js
- backend/src/schema/types/type/User.gql
Provide an API call, that allows an authenticated user to save the categories/topics with interest.
> feat: Save Category Settings

- webapp/components/FilterMenu/CategoriesMenu.vue
- webapp/layouts/default.vue
Unique class names for category filter menu. Category filter menu renders client only.
> fix: Category Filter Menu Client Only

- webapp/components/CategoriesSelect/CategoriesSelect.vue
- webapp/components/FilterMenu/CategoriesFilter.vue
- webapp/components/PostTeaser/PostTeaser.vue
- webapp/locales/de.json
- webapp/locales/en.json
- webapp/pages/post/_id/_slug/index.vue
Add tool tips for all topics on category filter menu and  category select.
> feat: 🍰 Tooltips For Topics

- .github/workflows/publish.yml
Implement automatic deployment for groups branch `5059-epic-groups`.
- fixes #5407
> chore: 🍰 Implement Automatic Deployment For Groups Branch '5059-epic-groups'

- webapp/components/AvatarMenu/AvatarMenu.spec.js
- webapp/components/AvatarMenu/AvatarMenu.vue
- webapp/components/Group/GroupButton.vue
- webapp/constants/groups.js
- webapp/layouts/default.vue
- webapp/locales/de.json
- webapp/locales/en.json
Have my groups in the user menu and configure groups button in header.
- fixes #5059
> feat: 🍰  Have My Groups In The User Menu And Configure Groups Button In Header

- webapp/constants/headerMenu.js
- webapp/layouts/default.vue
Make configurable header menu translatable.
fixes #5490
> feat: 🍰 Make Configurable Header Menu Translatable

- backend/src/db/seed.js
Add some simple posts to the groups
- fixes #5479
> feat: 🍰 Seed Posts In Groups

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/devops_ticket.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/ISSUE_TEMPLATE/refactor_ticket.md
- .github/ISSUE_TEMPLATE/release.md
- .github/PULL_REQUEST_TEMPLATE.md
updated issue templates to the latest version of https://github.com/ulfgebhardt/issue-templates - featuring release and some minor updates
- fixes #XXX
- relates #XXX
> feat:  :cake: Update Issue Templates

- webapp/components/Group/GroupList.spec.js
- webapp/components/Group/GroupList.vue
- webapp/components/Group/GroupMember.spec.js
- webapp/components/Group/GroupMember.vue
- webapp/graphql/User.js
- webapp/locales/de.json
- webapp/locales/en.json
- webapp/pages/group/edit/_id/members.vue
Find a network user by slug and add him to a group. this can only be done by the group owner.
- fixes #5384
> feat: 🍰 Group Invitation        

- webapp/components/FilterMenu/FilterMenu.vue
- webapp/layouts/default.vue
Move the category filter in filter menu
- fixes #5526
> refactor: 🍰 Category Filter In Filter Menu

- webapp/constants/logos.js
- webapp/layouts/default.vue
- webapp/pages/index.vue
Implement `LOGO_HEADER_CLICK` as configuration.
fixes #5523
> feat: 🍰 Implement `LOGO_HEADER_CLICK` As Configuration

- .github/workflows/publish.yml
> chore: 🍰 Remove Group Branchs `5059-epic-groups` Separate Auto-Deployment

- webapp/constants/logos.js
- webapp/layouts/default.vue
Updated the mobile screen header logo to route to external or internal URL according to change request from fork pull request.
- fixes https://github.com/Ocelot-Social-Community/Ocelot-Social/issues/5550
- related https://github.com/Ocelot-Social-Community/Ocelot-Social/pull/5572
> feat: 🍰 Header Logo Routing Update

- webapp/components/Group/GroupTeaser.vue
Fix group teaser.
- fixes #5570
> fix: 🍰 Fix Group Teaser

- backend/src/middleware/sluggifyMiddleware.js
- backend/src/middleware/slugifyMiddleware.spec.js
- backend/src/schema/resolvers/groups.spec.js
- webapp/components/Group/GroupForm.vue
Fixing the bug in edit slug setting of group.
fixes #5480
> fix: 🍰 Bug In Edit Slug Of Group

- webapp/components/ProgressBar/ProgressBar.vue
- webapp/constants/donation.js
Make donation progress bar color configurable.
fixes #5580
> feat: 🍰 Make Donation Progress Bar Color Configurable

- backend/src/middleware/excerptMiddleware.js
- webapp/graphql/groups.js
One of these: it took me one and a half hours for one line of code ...
- fixes #5510
> fix: 🍰 Update Group Avatar After Upload

- webapp/components/Registration/RegistrationSlideCreate.vue
- webapp/components/Registration/RegistrationSlideEmail.vue
- webapp/components/Registration/RegistrationSlideInvite.vue
- webapp/components/Registration/RegistrationSlideNoPublic.vue
- webapp/components/Registration/RegistrationSlideNonce.vue
a space has been added to the regsiter box
- fixes #4744
> fix: 🍰 Add Space In Register Box

- README.md
Add live demo to main readme.
fixes #5064
> docs: 🍰 Add Live Demo To Main Readme

- webapp/pages/post/_id/_slug/index.vue
Disable comment function on posts in groups for not group members
- fixes #5601
> fix: 🍰 Comments On Posts In Groups In Webapp

- .github/workflows/test.yml
- webapp/components/FilterMenu/CategoriesFilter.spec.js
- webapp/components/FilterMenu/CategoriesFilter.vue
- webapp/components/FilterMenu/EmotionsFilter.spec.js
- webapp/components/FilterMenu/EmotionsFilter.vue
- webapp/components/FilterMenu/FilterMenu.vue
- webapp/components/FilterMenu/FilterMenuSection.vue
- webapp/components/FilterMenu/FollowingFilter.spec.js
- webapp/components/FilterMenu/FollowingFilter.vue
- webapp/components/FilterMenu/LanguagesFilter.spec.js
- webapp/components/FilterMenu/LanguagesFilter.vue
- webapp/components/HeaderMenu/HeaderMenu.vue
- webapp/graphql/CategoryQuery.js
- rearranged,
- desktop view font and icon larger
- categories sorted by slug_asc
- fixes #5540
> refactor: 🍰 Refactor Design Of Category Filter In Filter Menu

- backend/src/schema/resolvers/groups.js
> fix: My Groups Count Includes Pending Membership

- .github/workflows/lint_pr.yml
> feat(other): semantic pullrequest workflow

- backend/src/db/seed.js
- webapp/components/HeaderMenu/HeaderMenu.vue
> fix(webapp): centralize mobile hamburger menu 

- backend/jest.config.js
- backend/package.json
- webapp/jest.config.js
- webapp/package.json
- webapp/yarn.lock
> test(other): jest coverage report in console

- backend/src/schema/index.js
> fix(backend): 🍰 Misspelled Notification

- webapp/pages/index.spec.js
- webapp/pages/index.vue
Provides query `categoryId` in route to set category filter by URL
- fixes #5677
> feat(webapp): 🍰 Params For Category Filter

- webapp/pages/donate.spec.js
- webapp/pages/imprint.spec.js
- webapp/pages/organization.spec.js
- webapp/pages/support.spec.js
> fix(webapp): clean up webapp unit tests

- backend/src/helpers/walkRecursive.js
- backend/src/middleware/xssMiddleware.js
Sanitizes the html of group description and description excerpt.
Additional argument to the walk recursive function to pass field names that should not be sanitized.
- fixes #5668
> fix(backend): sanitize group description

- webapp/components/HeaderMenu/HeaderMenu.vue
when scrolling down the navbar is hidden and when scrolling up it is displayed again.
- fixes #5750 
https://user-images.githubusercontent.com/1324583/213911172-f142d57c-2a3f-472e-9e30-4f99aa6cfa3c.mp4
https://user-images.githubusercontent.com/1324583/213911175-e4d9b872-8d34-4c34-9fb3-c8f773116992.mp4
> refactor(webapp): hide navbar by scroll down, show navbar by scroll up

- webapp/components/FilterMenu/FilterMenu.vue
- webapp/components/FilterMenu/FilterMenuComponent.vue
- webapp/layouts/default.vue
- webapp/locales/de.json
- webapp/locales/en.json
- webapp/pages/index.vue
If filters are set for 
- "Topics" 
- "Filters of users I follow". 
can be reset by X
- fixes #5818
> [WIP] feature(webapp): filter menu in content page

- backend/src/constants/groups.js
- webapp/constants/groups.js
- webapp/locales/de.json
- webapp/locales/en.json
* min length of group description to 50
* change text of grid filter button by Users I follow
- None
> fix(webapp): small changes for deploy 

- webapp/components/FilterMenu/CategoriesFilter.vue
- webapp/components/FilterMenu/FilterMenu.vue
- webapp/components/FilterMenu/FilterMenuComponent.vue
- webapp/components/HeaderMenu/HeaderMenu.vue
- webapp/constants/posts.js
- webapp/layouts/default.vue
- webapp/pages/index.vue
- there is a new constant **POST_ADD_BUTTON_POSITION_TOP** if this is true then it is displayed in the top area and hidden when scrolling. 
- additionally i have positioned the filter menu, the filter menu box better and ... as long as it is open it will not be hidden when scrolling the background anymore. 
- when you click save or all in the filter menu, the menu closes automatically. 
- in the browser the menu closes when you leave it with the mouse. 
- fixes #5907 
https://user-images.githubusercontent.com/1324583/217294481-8f79aad3-4230-4a23-881a-25ba08ec371e.mp4
> refactor(webapp): refacchange postion add content button, refactor mobile filter menu

- webapp/components/Category/index.vue
- webapp/components/PostTeaser/PostTeaser.vue
- webapp/pages/index.vue
filters colored which were selected by filter
- fixes #5819 
https://user-images.githubusercontent.com/1324583/217756112-93b8ebb0-b997-4765-85e8-818cf7b5b0fb.mp4
> feat(webapp): mark active filters on the posts

- webapp/components/AvatarMenu/AvatarMenu.vue
- webapp/components/HeaderMenu/HeaderMenu.vue
the navbar menu is closed for all links
- fixes #5955 
https://user-images.githubusercontent.com/1324583/217802062-0a079fb0-ad93-4753-9e1c-3cded8a9822a.mp4
> fix(webapp): close mobile menu on all links

- webapp/components/HeaderMenu/HeaderMenu.vue
- webapp/components/MasonryGrid/MasonryGrid.vue
- webapp/pages/index.vue
- fix post teaser width in mobile view
- fix close navbar menu if open by click of  logo
- fixes #5598
> fix(webapp): post teaser width in mobile view

- deployment/docker-compose.yml
- deployment/src/docker/maintenance.Dockerfile
- deployment/src/docker/webapp.Dockerfile
- webapp/plugins/i18n.js
- fixes https://github.com/Ocelot-Social-Community/Ocelot-Social/issues/6028
- fixes https://github.com/Ocelot-Social-Community/Ocelot-Social/issues/5981
> fix(other): fix maintenance page & maintenance build

- .github/dependabot.yml
- .github/workflows/test.yml
fix dependabot
- try to fix permissions problem on dependabot
- define weekly schedule
- complete `package-ecosystem` definitions ( `docker`,  `npm`, `github-actions`)
- remove all ignores
- potentially fixes: https://github.com/Ocelot-Social-Community/Ocelot-Social/issues/5974
> feat(other): fix dependabot

- .github/workflows/lint_pr.yml
exclude dependabot from pr title linting
- fixes #6084
> fix(other): exclude dependabot from pr title linting

- README.md
Add general information
update readme.md
- fixes #6089
> docs(other): update readme.md

- .github/dependabot.yml
dont rebase automatically to avoid workflow slots beeing used
- None
> fix(other): dependabot do not rebase

- .github/workflows/lint_pr.yml
lint pr only when there is a pullrequest not on every push
- None
> fix(other): lint pr only on pullrequest

- .github/workflows/publish-branded.yml
- .github/workflows/publish.yml
- cleanup publish workflow for non-branded version
- fixes https://github.com/Ocelot-Social-Community/Ocelot-Social/issues/6006
> refactor(other): ocelot publish workflows

- webapp/components/PostTeaser/PostTeaser.vue
- webapp/components/ShoutButton.vue
- webapp/components/_new/generic/BaseButton/BaseButton.story.js
- webapp/components/generic/SearchPost/SearchPost.vue
Change shout icon `bullhorn` to `heart-o`.
- fixes #6069
> feat(webapp): change shout icon `bullhorn` to `heart-o`

- webapp/components/Category/index.vue
- webapp/components/PostTeaser/PostTeaser.vue
Change icon color of active topics (categories) of post teaser.
- fixes #5983
> fix(webapp): change icon color of active topics (categories) of post teaser

- .github/workflows/test.yml
- cypress/cypress.json
> refactor(other): deactivate video recording & only upload screenshots, if tests fail for e2e tests

- backend/src/db/factories.js
do not delete migrations on db reset
- None
> fix(backend): do not delete migrations on db reset

- .github/workflows/publish.yml
- deployment/scripts/cluster.upgrade.sh
- deployment upgrade to specific version
- trigger build on stage
- None
> refactor(other): deployment upgrade to specific version, trigger build on stage

- webapp/components/MasonryGrid/MasonryGrid.vue
> fix(webapp): revert pr `on newsfeed add bigger y-gap between posts #6121`

- webapp/components/NotificationMenu/NotificationMenu.vue
> fix(webapp): close popover notification menu

- deployment/scripts/branded-images.build.sh
- deployment/scripts/cluster.maintenance.sh
- deployment/scripts/cluster.reseed.sh
- deployment/scripts/cluster.upgrade.sh
- deployment/scripts/secret.generate.sh
- deployment/scripts/secrets.decrypt.sh
- deployment/scripts/secrets.encrypt.sh
echo current configuration when running scripts. This will allow the user to interrupt the process when then wrong configuration is chosen.
- None
> feat(other): echo current configuration when running scripts

- .github/workflows/publish.yml
- deployment/scripts/branded-images.build.sh
- deployment/scripts/branded-images.upload.sh
deployment include GitHub run number on branded images
- None
> feat(other): deployment include GitHub run number on branded images

- webapp/pages/index.vue
> fix(webapp): popup filter max-width

- webapp/components/AvatarMenu/AvatarMenu.vue
- webapp/components/LocaleSwitch/LocaleSwitch.vue
- webapp/components/NotificationMenu/NotificationMenu.vue
- webapp/components/_new/generic/ProfileAvatar/ProfileAvatar.vue
- webapp/locales/de.json
- webapp/locales/en.json
Add tooltips to all menu icons.
- fixes #6184
Tooltip text for all menus:
> feat(webapp): add tooltips to all menu icons

- backend/src/db/migrations/20230329150329-article-label-for-posts.js
> feat(backend): add article label to posts

- deployment/src/kubernetes/templates/backend/Deployment.yaml
- deployment/src/kubernetes/templates/webapp/Deployment.yaml
reduce kubernetes memory limits. If this is not corrected the database cannot be started anymore on 2-Maschine Clusters.
- None
> fix(other): reduce kubernetes memory limits

- .github/workflows/publish.yml
> fix(other): workflow typo

- backend/src/graphql/posts.js
- backend/src/schema/resolvers/helpers/events.js
- backend/src/schema/resolvers/posts.js
- backend/src/schema/resolvers/posts.spec.js
- backend/src/schema/types/type/Post.gql
add parameters `eventEnd`  and `eventIsOnline`
- None
> feat(backend): add further event params

- backend/src/schema/resolvers/searches.js
- backend/src/schema/resolvers/searches/queryString.js
- backend/src/schema/resolvers/searches/queryString.spec.js
- webapp/components/generic/SearchableInput/SearchableInput.spec.js
- webapp/components/generic/SearchableInput/SearchableInput.vue
Remarks:
- Does not exclude functional characters as defined in the issue, but searches as soon as 3 characters are present (considering this negelectable)
- You can press enter even when there is one character which will result in you ending up on the search result page with the results for just one character search (considering this a feature)
- Also have the search refactored and simplified.
- fixes #6195
> fix(webapp): fix search for 3 chars

- webapp/graphql/groups.js
> fix(webapp): show avatar for group members

- backend/src/graphql/posts.js
- backend/src/schema/resolvers/helpers/events.js
- backend/src/schema/resolvers/posts.js
- backend/src/schema/resolvers/posts.spec.js
- backend/src/schema/types/type/Post.gql
> fix(backend): recover missing commit

- backend/src/schema/resolvers/notifications.js
> fix(backend): post type on notifications

- webapp/components/CategoriesSelect/CategoriesSelect.vue
- webapp/components/ContributionForm/ContributionForm.vue
When creating a post in a group, the categories of the group are set as default for the post.
- is there one?
> feat(webapp): default categories of group for posts in group

- deployment/docker-compose.yml
> fix(other): docker-compose for rebranding deployment

- backend/src/server.js
default to empty object in helmet
- None
> fix(backend): helmet fix

- deployment/TODO-next-update.md
Add missing todo in deployment readme 'TODO-next-update.md'.
- fixes #6323
> docs(other): add missing todo in deployment readme 'TODO-next-update.md'

- deployment/src/docker/backend.Dockerfile
corrected path in branded images for backend build folder(former dist)
- None
> fix(backend): corrected path in branded images for backend build folder(former dist)

- backend/src/db/migrations/20230608130637-add-postType-property.js
> feat(backend): migration to add postType property to existing posts

- backend/src/schema/resolvers/posts.js
- backend/src/schema/types/type/Post.gql
Do not only filter for the event start date, but for the event end date as well.
based on #6391 
- None
> feat(backend): show events not ended yet

- backend/Dockerfile
- deployment/src/kubernetes/templates/neo4j/ConfigMap.yml
- webapp/Dockerfile
- Fix neo4j config map
- Downgrade node version to 20.2 as it seems to cause probelms (see: https://forums.docker.com/t/getting-error-when-running-container-env-cant-execute-node-text-file-busy/136409)
- None
> fix(other): neo4j config map & node version

- backend/src/graphql/messages.ts
- backend/src/schema/resolvers/messages.spec.ts
- backend/src/schema/resolvers/messages.ts
- backend/src/schema/types/type/Message.gql
> feat(backend): message properties

- backend/package.json
- backend/scripts/build.copy.files.sh
- deployment/src/docker/backend.Dockerfile
fix branded build
the build folder contains a `src/` folder and therefore we need to reference it properly
the provider.json is an exception and might need another refactor?
- None
> fix(backend): fix branded build

- backend/package.json
- deployment/scripts/cluster.reseed.sh
- deployment/src/kubernetes/README.md
fix branded build (migration)
- fix migration path to `build/src/`
- update stage.ocelot.social reference
- None
> fix(backend): fix branded build (migration)

- deployment/src/docker/maintenance.Dockerfile
- deployment/src/docker/webapp.Dockerfile
fix branded build - rename files to js for the webapp
- conversion of ts files to js files
- updated stage.ocelot.social reference
- None
> fix(other): fix branded build - rename files to js for the webapp

- backend/src/schema/resolvers/rooms.spec.ts
- backend/src/schema/resolvers/rooms.ts
- webapp/layouts/default.spec.js
- webapp/layouts/default.vue
- webapp/store/chat.js
chat - do not allow to create room with self
- None
> fix(backend): chat - do not allow to create room with self

- deployment/TODO-next-update.md
update TODO-next-update.md for 2.7.0-470
- None
> docs(other): update TODO-next-update.md for 2.7.0-470

- backend/src/db/seed.ts
Seeds message for the chat.
There is chats between
- Huey & Peter: 60
- Huey & Jenny: 2000
- Jenny & 30 random users: 58 each
- None
> feat(backend): chat seed

- webapp/components/Chat/Chat.vue
> fix(webapp): show room header images.

- backend/src/graphql/rooms.ts
- backend/src/schema/resolvers/rooms.spec.ts
- backend/src/schema/types/type/Room.gql
- webapp/components/Chat/Chat.vue
- webapp/graphql/Rooms.js
- pagination for rooms
- fetch more rooms
- some code cleanup & simplifications
- fetch only the single room when in single-room mode
- fixes #6546
> feat(webapp): chat paginate rooms

- webapp/components/Chat/Chat.vue
- webapp/graphql/Messages.js
> feat(webapp): chat last seen in webapp

- backend/src/graphql/rooms.ts
- backend/src/middleware/permissionsMiddleware.ts
- backend/src/schema/resolvers/rooms.spec.ts
- backend/src/schema/resolvers/rooms.ts
- backend/src/schema/types/type/Room.gql
- webapp/components/ChatNotificationMenu/ChatNotificationMenu.vue
- webapp/graphql/Rooms.js
> feat(backend): unread rooms query

- backend/src/graphql/messages.ts
- backend/src/graphql/rooms.ts
- backend/src/middleware/chatMiddleware.ts
- backend/src/middleware/index.ts
- backend/src/schema/resolvers/messages.spec.ts
- backend/src/schema/resolvers/messages.ts
- backend/src/schema/resolvers/rooms.spec.ts
- backend/src/schema/resolvers/rooms.ts
- backend/src/schema/types/type/Room.gql
* CreateMessage returns full message object
* CreateRoom returns full room object
* lastMessage property for room
* unreadCount property for room
- None
> feat(backend): more room properties

- backend/src/schema/types/type/Room.gql
- webapp/components/Chat/Chat.vue
- webapp/graphql/Messages.js
> feat(webapp): mark messages as seen

- backend/src/db/seed.ts
removed promise all from seed
- None
> refactor(backend): removed promise all from seed

- .github/file-filters.yml
- .github/workflows/test-backend.yml
- .github/workflows/test-webapp.yml
To reduce test workflow runtime, we replace the Github artifact mechanism by its caching mechanism.
> refactor(other): cache docker images for backend webapp e2e testing

- backend/src/schema/resolvers/messages.ts
convert indexId to string (neo4j number problem)
This fixes the socket.
- None
> fix(backend): convert indexId to string (neo4j number problem)

- webapp/locales/de.json
- webapp/locales/en.json
- webapp/locales/es.json
- webapp/locales/fr.json
Change text for chat room search to `Filter chat rooms`.
- fixes #6591
> feat(webapp): change text for chat room search to `Filter chat rooms`

- backend/src/schema/resolvers/messages.ts
- backend/src/schema/resolvers/notifications.ts
- backend/src/schema/resolvers/rooms.ts
- backend/src/schema/types/type/Message.gql
- backend/src/schema/types/type/NOTIFIED.gql
- backend/src/schema/types/type/Room.gql
- webapp/components/Chat/Chat.vue
- webapp/components/ChatNotificationMenu/ChatNotificationMenu.vue
- webapp/components/NotificationMenu/NotificationMenu.vue
- webapp/graphql/Messages.js
- webapp/graphql/Rooms.js
- webapp/graphql/User.js
Fixes a security hole with the subscriptions (userId)
- None
> fix(backend): security subscriptions

- webapp/components/FilterMenu/FollowingFilter.vue
- webapp/components/FilterMenu/OrderByFilter.vue
- webapp/locales/de.json
Fix wrong labels in filter menu buttons.
- fixes #6655
> fix(webapp): fix wrong labels in filter menu buttons

- webapp/components/Chat/Chat.vue
Try to fix avatars.
- relates #6659
> fix(webapp): try to fix avatars

- webapp/components/Chat/Chat.vue
Fix 'm.avatar is null' error message.
- fixes #6668
> fix(webapp): fix 'm.avatar is null' error message

- webapp/components/Chat/Chat.vue
- webapp/plugins/vue-filters.js
> fix(webapp): fix proxyapiurl in chat rooms for the avatars

- backend/src/schema/resolvers/users/location.spec.ts
> fix(backend): cypher statement in user locales unit test

- cypress/cypress.config.js
> fix(other): increase cypress timeouts

- webapp/components/FilterMenu/FilterMenuComponent.vue
- webapp/pages/index.vue
Make filter menu visible if categories are inactive.
- fixes #6794
- blocked-by #6809
> fix(webapp): make filter menu visible if categories are inactive

- backend/src/jwt/decode.spec.ts
Generates a JWT in the unit test instead of having a static one (which expires)
- fixes #6855
> fix(backend): expired jwt in unit test

- .gitignore
- deployment/deployment.md
- deployment/scripts/cluster.backup.sh
- deployment/scripts/cluster.maintenance.sh
- deployment/scripts/cluster.neo4j.sh
- deployment/scripts/clusters.backup-multiple-servers.sh
- deployment/src/kubernetes/Backup.md
- docker-compose.yml
- neo4j/README.md
Temporary PR, because I commited into the wrong branch
- None
> 6812 script auto backups for kubernetes servers  database name as variable

- .github/workflows/publish.yml
Reverts Ocelot-Social-Community/Ocelot-Social#6654
> chore(other): revert pr - improve structure and readability of auto-generated changelog

- .github/workflows/deploy-documentation.yml
> refactor(other): fix build command in docs deploy workflow

- README.md
> refactor(other): replace deprecated testbadgelink in main readme file

- .vuepress/config/theme.js
- package-lock.json
- package.json
- fixes #7015
As on https://ocelot.social/ have on https://docs.ocelot.social/
> refactor(other): adapt docs website navbar and footer to ocelot.social website

- .vuepress/styles/palette.scss
> refactor(other): set ocelot color for docs website

- scripts/translations/normalize-locales.jq
- scripts/translations/normalize.sh
- webapp/locales/es.json
- webapp/locales/fr.json
- webapp/locales/it.json
- webapp/locales/nl.json
- webapp/locales/pl.json
- webapp/locales/pt.json
- webapp/locales/ru.json
- webapp/package.json
`yarn locales:normalize` added to scripts.
Copies the keys of the English locale file and to all other locale files (except German). If a value is present, it is set, else null.
We should discuss how this could be integrated in the CI. 
- relates #6952
> feat(webapp): normalize locale files

- webapp/locales/de.json
- webapp/locales/en.json
- webapp/locales/es.json
- webapp/locales/fr.json
- webapp/locales/it.json
- webapp/locales/nl.json
- webapp/locales/pl.json
- webapp/locales/pt.json
- webapp/locales/ru.json
> fix(webapp): remove reported unused locale keys

- .github/dependabot.yml
> refactor(other): group dependabot updates

- backend/src/schema/resolvers/posts.spec.ts
- backend/src/schema/resolvers/users/location.spec.ts
> fix(backend): fix backend tests by changing mapbox location coordinates

- deployment/deployment.md
- deployment/scripts/cluster.backend-bash.sh
- deployment/scripts/cluster.dashboard-token.sh
- deployment/scripts/cluster.dashboard-tunnel.sh
- deployment/scripts/cluster.neo4j-bash.sh
- deployment/src/kubernetes/DigitalOcean.md
- neo4j/README.md
Adjust docs for deployment, neo4j cypher commands, and have new scripts
- None
> chore(other): adjust docs for deployment, neo4j cypher commands, and have new scripts

- webapp/pages/notifications/index.vue
…ase-button
Notification page has unbranded button.
- fixes #7986
> fix(webapp): notification page has unbranded button

- frontend/src/assets/sass/tokens.module.scss
- webapp/constants/manifest.js
- webapp/constants/metadata.js
Change theme color to be brandable.
- fixes #8003
> fix(webapp): change theme color to be brandable

- webapp/components/Badges.vue
In #8024 changes in `webapp/components/Badge.vue` have accidentally been merged.
This pull request reverts them.
- relates #8024
> fix(other): revert a change, which accedentally was merged

- backend/src/schema/resolvers/comments.ts
- backend/src/schema/resolvers/observePosts.spec.ts
- backend/src/schema/types/type/Comment.gql
- webapp/graphql/Fragments.js
> feat(backend): observing status of the post after creating comment

- backend/src/db/migrations/20250331130323-author-observes-own-post.ts
> feat(backend): migrate observes relation between author and post

- frontend/package-lock.json
fix frontend package lock.
Whenever you start the docker you get a changed `frontend/package-lock.json`
- None
> fix(frontend): fix frontend package lock

- backend/src/schema/resolvers/groups.spec.ts
- backend/src/schema/resolvers/groups.ts
typo in groups resolver
- None
> fix(backend): typo in groups resolver

- backend/src/middleware/notifications/posts-in-groups.spec.ts
> feat(backend): test that there is no email sent when no notification

- backend/src/schema/resolvers/users.ts
block user
blocking a user resulted in an error. Blocking was not possible.
- made it possible
- simplified query into one
- None
> fix(backend): block user

- scripts/release.sh
release script does not include commits
Previously:
- None
> fix(release): fix release script

- .gitignore
I need this to work on a nuxt 3 version of maintenance, without trouble.
> feat(other): add .nuxt to gitignore

- backend/src/middleware/notifications/notificationsMiddleware.online-status.spec.ts
- backend/src/middleware/notifications/notificationsMiddleware.ts
> feat(backend): no notification mails to users online

- backend/src/middleware/notifications/notificationsMiddleware.mentions-in-groups.spec.ts
> fix(backend): flaky notifications mentioned in groups unit test

- backend/src/middleware/notifications/notificationsMiddleware.emails.spec.ts
- backend/src/middleware/notifications/notificationsMiddleware.mentions-in-groups.spec.ts
- backend/src/middleware/notifications/notificationsMiddleware.ts
> feat(backend): only one email is sent although more notifications are triggered

- backend/src/graphql/types/type/User.gql
- backend/src/schema/resolvers/users.spec.ts
- backend/src/schema/resolvers/users.ts
allow to set selected badge-slot to null
Free a specific badge slot by setting it to null
- None
> refactor(backend): allow to set selected badge-slot to null

- backend/Dockerfile
- backend/src/config/index.ts
- backend/src/middleware/branding/brandingMiddlewares.ts
- backend/src/middleware/index.ts
branding middlewares
allow the rebanding to provide middlewares
- None
> feat(backend): branding middlewares

- webapp/constants/links.js
> fix(webapp): fix ocelot.social link for imprint and donation

- backend/src/graphql/types/type/User.gql
- backend/src/schema/resolvers/users.spec.ts
- backend/src/schema/resolvers/users.ts
calculate distance between current user and queried user. Distance is in Kilometers.
Login Jenny from Paris
```
mutation {login(email: "user@example.org", password: "1234")}
```
Query distanceToMe of current user = null
```
query {currentUser{name distanceToMe}}
{
"data": {
"currentUser": {
"name": "Jenny Rostock",
"distanceToMe": null
}
}
}
```
Query distance of Huey from Paris user = 0
```
query {User(id: "u4"){name distanceToMe}}
{
"data": {
"User": [
{
"name": "Huey",
"distanceToMe": 0
}
]
}
}
```
Query distance of Peter Lustig from Hamburg user = 0
```
query {User(id: "u1"){name distanceToMe}}
{
"data": {
"User": [
{
"name": "Peter Lustig",
"distanceToMe": 877
}
]
}
}
```
Query distance of Huey from Nowhere = null
```
query {User(id: "u5"){name distanceToMe}}
{
"data": {
"User": [
{ …
```
> feat(backend): distanceToMe

- backend/scripts/build.copy.files.sh
fix emails in production
- None
> fix(backend): fix emails in production

- backend/scripts/build.copy.files.sh
copy email templates & locales to correct folder
- None
> fix(backend): copy email templates & locales to correct folder

- backend/src/emails/__snapshots__/sendChatMessageMail.spec.ts.snap
- backend/src/emails/__snapshots__/sendEmailVerification.spec.ts.snap
- backend/src/emails/__snapshots__/sendNotificationMail.spec.ts.snap
- backend/src/emails/__snapshots__/sendRegistrationMail.spec.ts.snap
- backend/src/emails/__snapshots__/sendResetPasswordMail.spec.ts.snap
- backend/src/emails/__snapshots__/sendWrongEmail.spec.ts.snap
- backend/src/emails/sendEmail.ts
Email from is now: `APPLICATION_NAME <DEFAUL_EMAIL_SENDER>`
- None
> fix(backend): correct email from field

- backend/src/graphql/queries/Group.ts
- backend/src/graphql/resolvers/inviteCodes.spec.ts
- backend/src/graphql/resolvers/inviteCodes.ts
- backend/src/graphql/resolvers/users.ts
invite codes - hotfix 1
- None
> fix(backend): invite codes - hotfix 1

- webapp/locales/de.json
fix locales errors (German)
- None
> fix(webapp): fix locales errors (German)

- backend/src/graphql/resolvers/registration.ts
fix registration with invite code
- None
> fix(backend): fix registration with invite code

- webapp/components/InviteButton/InviteButton.vue
- webapp/components/_new/features/Invitations/Invitation.vue
- webapp/pages/groups/edit/_id/invites.vue
- Fixes long comment overflow.
There is some underlying problem with flex box and overflows. A better solution could be to use a grid, but this was the fastest I would come up with.
- Fixes hidden group name appearance
> fix(webapp): fix layout break and hidden group name appearance

- backend/src/middleware/permissionsMiddleware.ts
- webapp/components/Registration/RegistrationSlideCreate.vue
- webapp/graphql/InviteCode.js
> feat(webapp): redirect to group after registration with invite to group

- webapp/components/Dropdown.vue
- webapp/components/InviteButton/InviteButton.vue
Introduces `noMouseLeaveClosing` property on `Dropdown` and enable it for invitiations in menu.
> fix(webapp): show invititation dropdown until user clicks somewhere else

- webapp/locales/de.json
> fix(webapp): fix typo in german translation

- webapp/assets/styles/main.scss
Maybe fixes flickering when hovering user teaser.
> fix(webapp): fix flickering

- backend/src/graphql/resolvers/statistics.ts
fix statistics: reports
-> Typo reporting `InviteCodes` not `Reports`.
- None
> fix(backend): fix statistics: reports

- backend/src/graphql/resolvers/inviteCodes.spec.ts
- backend/src/middleware/permissionsMiddleware.ts
allow to query user id & slug
- None
> fix(backend): hotfix - allow more user fields to be queried

- webapp/pages/groups/_id/_slug.vue
> fix(webapp): group categories

- frontend/src/assets/sass/tokens.module.scss
- webapp/assets/_new/styles/tokens.scss
- webapp/components/ComponentSlider/ComponentSlider.vue
- webapp/components/EnterNonce/EnterNonce.vue
- webapp/components/PageFooter/PageFooter.vue
- webapp/components/PasswordReset/Request.vue
- webapp/components/Registration/EmailDisplayAndVerify.vue
- webapp/components/Registration/RegistrationSlideCreate.vue
- webapp/components/Registration/RegistrationSlideEmail.vue
- webapp/components/Registration/RegistrationSlideInvite.vue
- webapp/components/Registration/RegistrationSlideNonce.vue
- webapp/components/Registration/RegistrationSlider.vue
- webapp/components/Registration/Signup.vue
- webapp/components/_new/generic/BaseButton/BaseButton.vue
- webapp/layouts/no-header.vue
- webapp/locales/de.json
- webapp/locales/en.json
- webapp/locales/es.json
- webapp/locales/fr.json
- webapp/locales/it.json
- webapp/locales/nl.json
- webapp/locales/pl.json
- webapp/locales/pt.json
- webapp/locales/ru.json
- webapp/pages/password-reset.vue
- webapp/pages/password-reset/request.vue
- restyled bullets for slider
- relocated back links
- removed icons
- None
New Layout:
- provides enough space also for longer button names
- layout became more clear for user - less distractions 
- slider bullets became easier to recognize as such
> fix(webapp): optimize registration layout

- backend/src/graphql/resolvers/attachments/attachments.ts
Apparently Hetzner returns locations without protocol. So we add it if necessary.
> fix(backend): add protocol if missing

- package-lock.json
- package.json
- yarn.lock
remove expect package as this is a jest specific package, its not required.
See: https://www.npmjs.com/package/expect
- fixes https://github.com/Ocelot-Social-Community/Ocelot-Social/pull/8719
> fix(other): remove expect package

- .github/workflows/test.lint_pr.yml
revert fed951b3 amannn/action-semantic-pull-request
- related https://github.com/amannn/action-semantic-pull-request/issues/294
- related https://github.com/Ocelot-Social-Community/Ocelot-Social/pull/8830
> fix(workflow): revert fed951b3 amannn/action-semantic-pull-request

- backend/src/db/migrations/20250502230521-migrate-to-s3.ts
fix s3 migration
Background:
I could not migrate wir.social as apparently i run into a rate limit of subsequent requests getting `Bucket not found`.
This PR fixes this and is currently deployed on wir.social.
Migration takes longer but works.
This was the error thrown
```
NoSuchBucket: The specified bucket does not exist
```
- None
> fix(backend): fix s3 migration

- .github/workflows/test.lint_pr.yml
> refactor(workflow): pr titles - allow scope styleguide
